meta_product_name: "Crescendo"
meta_title: "Crescendo - Explore all possibilities of music"
meta_description: "Crescendo is a website to find all you want about music, in this first version video and lyrics are available."
meta_image: "landing.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
